[project]
name = "ecommerce-project"
version = "0.1.0"
description = ""
authors = [
    {name = "IVAN",email = "ivan.ustimov.2012@mail.ru"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black (>=25.9.0,<26.0.0)",
    "flake8 (>=7.3.0,<8.0.0)",
    "isort (>=6.1.0,<7.0.0)",
    "pytest (>=8.4.2,<9.0.0)",
    "pytest-cov (>=7.0.0,<8.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203"]
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "htmlcov",
    ".idea"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
addopts = "-v --strict-markers"

[tool.coverage.run]
source = ["src"]
omit = ["src/main.py"]
